package rushilrs_CSCI201_Assignment4;

// code generated by https://www.jsonschema2pojo.org/
public class FinnHubObject {
	private Float c;

	private Float d;

	private Float dp;

	private Float h;

	private Float l;

	private Float o;

	private Float pc;

	private Integer t;

	public Float getC() {
		return c;
	}

	public void setC(Float c) {
		this.c = c;
	}

	public Float getD() {
		return d;
	}

	public void setD(Float d) {
		this.d = d;
	}

	public Float getDp() {
		return dp;
	}

	public void setDp(Float dp) {
		this.dp = dp;
	}

	public Float getH() {
		return h;
	}

	public void setH(Float h) {
		this.h = h;
	}

	public Float getL() {
		return l;
	}

	public void setL(Float l) {
		this.l = l;
	}

	public Float getO() {
		return o;
	}

	public void setO(Float o) {
		this.o = o;
	}

	public Float getPc() {
		return pc;
	}

	public void setPc(Float pc) {
		this.pc = pc;
	}

	public Integer getT() {
		return t;
	}

	public void setT(Integer t) {
		this.t = t;
	}

}
